### Get all customers
GET http://localhost:5144/api/customers/
Accept: application/json

###

### Create a customer
POST http://localhost:5144/api/customers
Content-Type: application/json

{
  "firstName": "Valentinos",
  "lastName": "Koutekidis",
  "email": "valentinos@outlook.com",
  "phoneNumber": "6941234567"
}